spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/iam_monitoring
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
  elasticsearch:
    uris: ${ELASTICSEARCH_URL}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM:iam-platform}

logging:
  level:
    root: INFO
    com.iam.platform: INFO
