apiVersion: v1
kind: Service
metadata:
  name: iam-admin-service
  labels:
    app: iam-admin-service
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: http
  selector:
    app: iam-admin-service
