spring:
  profiles:
    active: native,dev
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_config
    username: iam_admin
    password: iam_secret_2026
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/iam-platform

logging:
  level:
    com.iam.platform: DEBUG
    org.springframework.security: DEBUG
