apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-gateway
  labels:
    app: iam-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iam-gateway
  template:
    metadata:
      labels:
        app: iam-gateway
    spec:
      containers:
        - name: iam-gateway
          image: rikreay/iam-gateway:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: CONFIG_SERVER_HOST
              value: "iam-config-service"
            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: iam-platform-config
                  key: keycloak-url
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: iam-platform-config
                  key: redis-host
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: iam-platform-secrets
                  key: redis-password
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
