spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/iam-platform
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${CORS_ORIGINS}

logging:
  level:
    root: INFO
    com.iam.platform: INFO
