spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/iam-platform
  data:
    redis:
      host: localhost
      password: redis_secret_2026
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:4200
              - http://localhost:3000
              - http://localhost:5173

logging:
  level:
    com.iam.platform: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
