server:
  ssl:
    enabled: ${SSL_ENABLED:false}

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/iam_governance
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    producer:
      acks: all
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM:iam-platform}

keycloak:
  admin:
    server-url: ${KEYCLOAK_URL}
    realm: master
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}

logging:
  level:
    root: WARN
    com.iam.platform: INFO
