package com.iam.platform.common.enums;

public enum DocumentType {
    NATIONAL_ID_CARD,
    PASSPORT,
    BIRTH_CERTIFICATE,
    CERTIFICATE_OF_INCORPORATION,
    PATENT_TAX_CERTIFICATE,
    VAT_CERTIFICATE,
    NGO_REGISTRATION,
    GOVERNMENT_DECREE,
    BOARD_RESOLUTION,
    POWER_OF_ATTORNEY,
    APPOINTMENT_LETTER,
    DELEGATION_LETTER,
    MOU
}
