package com.iam.platform.common.enums;

public enum EntityType {
    GOVERNMENT_MINISTRY,
    GOVERNMENT_DEPARTMENT,
    STATE_ENTERPRISE,
    MUNICIPALITY,
    COMMUNE,
    PRIVATE_LLC,
    SINGLE_MEMBER_LLC,
    PUBLIC_LIMITED,
    BRANCH_OFFICE,
    REPRESENTATIVE_OFFICE,
    SOLE_PROPRIETOR,
    PARTNERSHIP,
    LOCAL_NGO,
    INTERNATIONAL_NGO,
    ASSOCIATION,
    FOREIGN_MISSION
}
