package com.iam.platform.common.enums;

public enum RepresentativeRole {
    LEGAL_REPRESENTATIVE,
    AUTHORIZED_SIGNATORY,
    TAX_REPRESENTATIVE,
    FINANCE_OFFICER,
    HR_MANAGER,
    IT_ADMINISTRATOR,
    COMPLIANCE_OFFICER,
    BRANCH_MANAGER,
    PROJECT_COORDINATOR,
    MUNICIPAL_OFFICER,
    GOVERNMENT_OFFICER,
    DELEGATED_USER,
    EXTERNAL_AUDITOR
}
