apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iam-platform

resources:
  - namespace.yaml
  - gateway/deployment.yaml
  - gateway/service.yaml
  - gateway/hpa.yaml
  - core-service/deployment.yaml
  - core-service/service.yaml
  - core-service/hpa.yaml
  - tenant-service/deployment.yaml
  - tenant-service/service.yaml
  - tenant-service/hpa.yaml
  - audit-service/deployment.yaml
  - audit-service/service.yaml
  - audit-service/hpa.yaml
  - xroad-adapter/deployment.yaml
  - xroad-adapter/service.yaml
  - xroad-adapter/hpa.yaml
  - config-service/deployment.yaml
  - config-service/service.yaml
  - notification-service/deployment.yaml
  - notification-service/service.yaml
  - notification-service/hpa.yaml
  - admin-service/deployment.yaml
  - admin-service/service.yaml
  - admin-service/hpa.yaml
  - monitoring-service/deployment.yaml
  - monitoring-service/service.yaml
  - monitoring-service/hpa.yaml
  - keycloak/statefulset.yaml
  - keycloak/service.yaml

commonLabels:
  app.kubernetes.io/part-of: rikreay-iam-platform
